name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Initialize Terraform
      working-directory: ./files
      run: terraform init

    - name: Plan Terraform changes
      working-directory: ./files
      run: terraform plan -no-color

    - name: Apply Terraform changes
      working-directory: ./files
      run: terraform apply -auto-approve
      if: github.event_name == 'push'  # Aplicar apenas em push, não em pull requests
